set nocompatible
set nu
syntax on
filetype indent on
set autoindent
set ic
set hls
set lbr
colorscheme desert256
set tabstop=4
set shiftwidth=4
set expandtab

autocmd BufNewFile,BufRead *.json set ft=javascript

